import { Assessment } from "./data";

const createFluency = (id: string, name: string, grade: string, text: string): Assessment => ({
  id,
  name,
  grade,
  type: "fluency",
  text,
  words: text.split(/\s+/).filter(w => w.length > 0).map(w => ({ word: w }))
});

export const fluency2Assessments: Assessment[] = [
  createFluency("orf.2.1", "ORF.2.1 Drums", "Grade 2", "I like playing the drums. Drums help keep music from speeding up or slowing down. Drums were made a long time ago and can be found in a lot of different places. Playing the drums can be hard, because you need to do a lot at the same time. You can hit the drums with sticks or by stepping on a pedal. Drums can be played fast or slow but if you play too fast, you can hurt your hands. Drums can be big or small and can make a lot of different noises when you hit them. When you play the drums, it can be as loud as you want. Wearing ear plugs helps keep you safe from loud sounds. A lot of people playing the drums can flip and spin the sticks in their hands when they are playing. It takes a long time to learn to play the drums like that. Some people start playing the drums when they are little kids. Other people start playing the drums when they get older. Drums are played in a lot of different kinds of music. Try to see if you can hear the drums playing in your favorite music."),
  createFluency("orf.2.2", "ORF.2.2 Pop's Peach Stand", "Grade 2", "I like helping at Pop’s peach stand in the summer. My Pop lives far away, but I spend each summer on his farm. Pop grows hundreds of peach trees on his farm. My mom says that Pop’s peaches are the sweetest in the South. That’s why people come from all over to get to Pop’s farm. My Pop grew up on the peach farm. He started working with his granddad when he was small. Pop became an expert on peach trees. Each summer, Pop teaches me about his farm and how the peach trees grow. Pop waits until the peaches are perfectly ripe before he lets us pick them. When Pop decides that the peaches are ripe, he opens his farm and peach stand. Visitors can pick their own peaches on the farm or pay for a basket of peaches at the stand. Most days, I help at the peach stand. Lots of cars stop at Pop’s stand on the way to town. I greet each person and fill the baskets with peaches. Each basket of peaches costs five dollars. Last summer, one man got fifteen baskets of peaches! I told my Pop he must be rich. My Pop said that he’s just glad people like his peaches so much. I think Pop’s peaches are the best in the world."),
  createFluency("orf.2.3", "ORF.2.3 Babe Ruth", "Grade 2", "Babe Ruth was one of the best baseball players ever. He grew up in Baltimore and got in trouble a lot. He learned how to work hard in school and started playing baseball. Babe was so good at baseball that he got to play as his job. He got a job playing baseball when he was just nineteen years old. He was so young that his friends called him “Babe.” He was called by many other names but is best known as Babe. First, he played for Boston. He played for Boston for six years. Later, he was traded and played for the New York Yankees. Babe stayed in New York and played with the Yankees for fifteen years. He pitched and hit left-handed. Babe could hit hard. When he stopped playing baseball, he had more home runs than anyone else. Babe also pitched the ball. Nobody else could hit and pitch the ball like him. After Babe stopped playing baseball, nobody was as good as him for a long time. Only a few players have ever been able to hit and pitch like he did. Babe Ruth is now in the Baseball Hall of Fame. He is still one of the best baseball players of all time."),
  createFluency("orf.2.4", "ORF.2.4 Lucky Penny", "Grade 2", "Every Friday after school, Mom and I walk down the street to visit my aunt and cousins. On our walk last week, I spotted something shiny on the ground. I picked it up and realized I found a penny! “What did you find?” my mom asked. “A penny!” I replied. “Keep it safe,” she said,” Finding a penny brings you good luck.” I stuck it in my pocket to show my cousin when we got to their house. Once we got to their house, I was excited to show my cousin what I found. “Kelly!” I yelled, “I found something special on the way here. I can’t wait to show you!” We ran up the stairs to her bedroom so that I could show off my lucky penny. When I put my hand in the pocket of my pants, the penny was gone! I pulled out my pocket to find that there was a big hole. “Oh no! My penny is gone!” I said. What would happen now? Would I be unlucky? Mom said that it was getting too dark to try and find it outside. I was upset that I could not go out to find my new treasure. I took off my shoes to stay inside when something fell out of my sock. It was my penny! I guess I had been very lucky all along."),
  createFluency("orf.2.5", "ORF.2.5 The Sun", "Grade 2", "Our sun is many things. It is a huge ball of gas. It is a star. It is the center of our solar system and larger than all eight planets put together. Our sun gives us light and warmth. Without it, plant and animal life cannot survive. We might not see the sun at night or on a rainy, cloudy day, but it is still there. We say the sun rises in the morning and sets in the evening, but that is not true. The sun does not really move across the sky. It just looks that way because Earth is spinning. That means we are spinning, too! In the morning, we spin toward the sun, so it appears low in the sky. At noon, we directly face the sun, so it appears high in the sky. When the sun looks like it is setting, we are spinning away from it. At night, we are turned away from the sun. How far away from us is the sun? On a hot, summer day, it can feel close. In fact, the sun is quite far away — ninety-three million miles from Earth! It is so far away that it takes more than eight minutes for the sun’s light to reach our eyes."),
  createFluency("orf.2.6", "ORF.2.6 Cooking with Oma", "Grade 2", "Every weekend I go to visit my Oma and spend the night at her house. It is so fun because we do many activities together. We play games, weed her garden, walk in the neighborhood, and watch movies. But, my favorite activity is cooking! Oma makes a big pot of soup each weekend, and I get to help. First, we pick potatoes, onions, and peas out of the garden. After we wash them, we toss them into a big pot of hot water! We add chicken, spices, salt, and pepper. We set an alarm, so we will know when it is done. The best part is when we wait for the soup to cook. We play games until the timer makes a loud noise. When the timer beeps, we both jump up and yell, “Soup’s on!” Then we laugh and get big bowls and spoons. Oma puts a candle on the table, we get fancy napkins, and we dig in! Oma can eat soup fast, so she says whoever gets finished first gets to go first in the next game we play! We both laugh and smile! Making soup with Oma is the best part of visiting her on the weekend!"),
  createFluency("orf.2.7", "ORF.2.7 Fall Hike", "Grade 2", "Emma and her foster parents plan a family activity every weekend. This weekend they are taking Emma on her first hike. It is the first Friday in October and Emma gets home from school. That afternoon, they all sit down to talk about their hike. “Going for a hike is a great family activity to do together!” says Emma’s foster dad, Luka. He explains that a hike is a long walk in the woods. “We will follow the hiking trail and see lots of nature.” says Luka. “Fall is the best time of year to go for a hike!” says Emma’s foster mom Nora. “What makes fall a very special time for hiking?” asks Emma. Nora says, “Fall is so great because the leaves always change into pretty colors. They fall off the trees and crunch under your feet.” “Fall is also great because the animals are very active. We may see them searching for food or laying in the sunshine to get warm. We could even see flocks of birds flying south for the winter,” says Luka. Nora adds that fall weather is perfect for hiking. She says, “Fall air is crisp and the temperature is perfect. It is not very hot and not very cold.” Emma says, “This sounds so fun! I am excited for our first hike in the fall together!”"),
  createFluency("orf.2.8", "ORF.2.8 The Spelling Test", "Grade 2", "Edwin woke up Friday morning feeling excited. He had studied all week for today’s spelling test. Edwin was a strong speller, but he knew that the test was going to be a hard one. Grandma made his favorite breakfast for the special day: eggs and potatoes. Before Edwin left for the bus, Grandma gave him a hug and said, “Remember that you are not only my smart boy, but you are also my brave boy.” While sitting on the bus later, Edwin kept thinking to himself, “I am smart and I am brave, I am smart and I am brave.” When he walked into class, Edwin could tell everyone was talking about the test. His best friend, Dee, looked nervous. Edwin walked over and said, “Don’t worry, Dee. You are smart and brave! You will do a great job.” Soon, Edwin’s teacher walked into the classroom and told the class it was time to take the spelling test. The test was just as hard as Edwin imagined. But he said to himself, “I am smart and I am brave.” He took his time on each word and tried his very best. At the end of the day Edwin got his spelling test back. He got a perfect score!"),
  createFluency("orf.2.9", "ORF.2.9 Legs and Feet", "Grade 2", "Legs and feet can do so many things! Dog legs dig and run for balls. They scratch on doors to say, “let me in”! Frog legs are long and smooth. They jump and swim in ponds. Cat legs are soft and like to rest in the sun. Cat feet have claws that can scratch and climb. Horse legs are strong to help them gallop and trot. Bird feet are thin and sharp. They help them gather sticks for nests. Bats have feet that are strong and can hold on to branches so they can sleep upside down. Spiders have so many legs! They help spin a web and make traps for bugs. Rabbits have big strong back legs and very big feet that help them hop through the garden and hide from the farmer. Lizards have sticky feet to help them go up trees and look for bugs to eat. A duck has feet that look like a flipper. Their feet help them swim and dive. Grasshoppers have long legs so they can jump and hop from tree to tree. Crickets use their legs to sing songs and call to their friends. A worm has no legs or feet at all but that does not stop it!"),
  createFluency("orf.2.10", "ORF.2.10 Backyard Camping", "Grade 2", "On Friday night, Beth got her red tent out of the bag and spread it out on the backyard lawn. Her friend Rayvon saw her and came over. “What are you doing?” he asked. Beth explained, “I was going to go camping this weekend. But the campsite was full, so now we can’t go. My mom and I are going to camp in the backyard instead. I can’t wait!” She started to take the tent poles out of the bag as Rayvon watched. “That sounds fun!” he said. Together, they carefully put the poles in the loops in the tent. The red tent started to take shape! After the poles were in the tent, they used a mallet to push stakes into the grass. The stakes kept the tent from blowing away or moving. Finally, they brought sleeping bags out from Beth’s house and put them inside the tent. The sky was getting darker because the sun started to go down. Rayvon heard his mom calling him. “Have a fun campout!” he said as he went home. Beth’s mom lit the grill so that they could eat hot dogs and grilled corn on the cob. After that, Beth and her mom got into the red tent and wiggled down into their sleeping bags. They were ready for the backyard campout!")
];
