import { Assessment } from "./data";

const createFluency = (id: string, name: string, grade: string, text: string): Assessment => ({
  id,
  name,
  grade,
  type: "fluency",
  text,
  words: text.split(/\s+/).filter(w => w.length > 0).map(w => ({ word: w }))
});

export const fluency3Assessments: Assessment[] = [
  createFluency("orf.3.1", "ORF.3.1 Sunday Dinner", "Grade 3", "Each Sunday, my dad cooks a large meal for my family. He makes burgers and hot dogs on the grill behind our apartment building. He enjoys making fries by cutting potatoes with a knife, and he also makes green beans that he steams in a large pot. My uncle brings the buns, and my grandmom brings apple pie or a homemade cake. Every now and then, my dad invites friends and neighbors to our dinner, too. We might have eleven kids and fifteen grownups! We gather on the grass by the grill where there are a few picnic tables, and the adults often bring chairs. While we wait for the burgers, we shoot hoops or play tackle football. The older kids have the job of watching the toddlers and babies. The grownups just sit around and chat with each other. I hear them giggle and tell stories that make them roll with laughter. They play cards, too, if it's not windy. After the meal, the kids help clean by taking a large bag to gather trash consisting of napkins and plates. We make it a game and count how long it takes to clean it all. We carry the dirty dishes and cups inside to the kitchen and scrub them in the sink. Sunday dinners are a favorite gathering of mine."),
  createFluency("orf.3.2", "ORF.3.2 Cat Moods", "Grade 3", "How can you tell what a cat is feeling when it can't talk to you? By watching how the cat is acting, you can get a good idea if it is happy or upset. When cats are angry or scared, they make their body as big as they can. The hair on their body and on their tail stands on end. They also arch their back. Cats might hiss or growl when they are upset. When a cat is happy to see you, it may bump the top of its head against your legs. This is called bunting. Cats have special glands around their head. When they rub their head on you, they are marking you with their smell. Most of the time, cats purr when they are content, happy, or relaxed. Purring is a deep rumbling sound that cats make by breathing while they vibrate muscles in their throat. If you are petting your cat and she is purring, you know that she is probably in a good mood. However, some cats purr when they are sick or in pain, so it is important to look at how the cat is holding its body while it is purring. By watching the cat's behavior, you can tell a lot about how the cat is feeling."),
  createFluency("orf.3.3", "ORF.3.3 Looking at Clouds", "Grade 3", "Blaze and Laila live in the same neighborhood and are also in the same class at school. They are in the fourth grade and walk to school together every day. Lately in science class, they have been learning that clouds are made of droplets of water and ice. They decide to stop at the park on the way home from school to gaze at the clouds in the sky. After school, Laila and Blaze race to the park nearby and select a spot in the grassy field perfect for observing clouds. They lay down on the ground and use their hands to shield their faces from the bright sun. \"I see many fluffy clouds floating in the sky. They look like clumps of cotton.\" says Laila. Blaze laughs and says, \"I think they look more like mashed potatoes rather than cotton.\" He points to the left, \"This cloud kind of looks like a crocodile.\" \"I can plainly see the tail! I think that it looks like a rabbit, though!\" says Laila. She points to the right and says, \"That cloud looks like an eagle. Can you see the grand wings?\" Blaze nods his head before standing up. He says, \"I enjoyed looking at the clouds this afternoon, but we should start walking home. I realize it will be dinner time soon and I am getting hungry.\"")
];
