import { Assessment } from "./data";

const createFluency = (id: string, name: string, grade: string, text: string): Assessment => ({
  id,
  name,
  grade,
  type: "fluency",
  text,
  words: text.split(/\s+/).filter(w => w.length > 0).map(w => ({ word: w }))
});

export const fluency1Assessments: Assessment[] = [
  createFluency("orf.1.1", "ORF.1.1 Cars", "Grade 1", "Cars help us get to new places. Cars come in all different colors. Cars can be big or small. Cars can be fast or slow. Most cars need gas to drive. You have to put gas in the car before you can drive. A lot of gas will make the car drive for a long time. Make sure you put on your seatbelt! It will keep you safe in a crash. Cars drive on tires. Tires are round and roll on the road. A lot of cars can drive on the same road. Too many cars on the road can make driving slow. If you drive too fast, you will get in trouble. Lights tell us how to drive. Green lights mean cars can drive. Red lights mean cars need to stop. Yellow lights mean be careful. Cars also have lights on them. Lights on the front help you see. Lights on the back come on when you stop. You can turn on lights when you want to turn. Do you like to ride in cars?"),
  createFluency("orf.1.2", "ORF.1.2 New Glasses", "Grade 1", "Last year, I did not like school. I had to sit in front of the class. It was hard to see the letters on my paper. I could not see the letters on the board. Every day when I got home, I felt tired. My head would hurt. Sometimes I would cry. One day, I went to see the eye doctor. She could help me see better. The doctor showed me numbers on the wall. Some were too small for me to see. The doctor told me I needed to wear glasses. She said I could pick them out. I could choose a color. There were many kinds. I chose blue glasses. Blue is the best color. When I put them on, I could see all the numbers. The doctor said I could wear my glasses home. Now I am in the first grade. I have one red pair and one blue pair of glasses. I can sit in the front or back of the class. I can see much better. I can read everything on my paper. I can even read words far away. My friends want glasses too. I love my glasses and now I like school!"),
  createFluency("orf.1.3", "ORF.1.3 Toys", "Grade 1", "Do you like toys? Toys are fun! Kids like to play with toys. Toys can be tiny, and toys can be huge. Toys come in all sorts of shapes and colors too. Cars, dolls, and blocks are more toys that you may have seen. Games are toys that you can play. Teddy bears, robots, and puzzles are toys too. A lot of kids have a favorite toy. Some toys are made for little kids. Other toys are best for bigger kids. You can play games by yourself or with a friend. Toys can help you pretend when you play. Toys are sold in stores or online. Toys come wrapped up. If you save your money, you can buy a toy. You may get a toy as a gift as well. Many kids like to get lots of one toy. Some toys must be put together. You can keep all your toys in a big bin. That way, you can find your toys. You can share your toys with your brother or sister. Your friends might want to play with your toys, too. What is your favorite toy?"),
  createFluency("orf.1.4", "ORF.1.4 Going to the Doctor", "Grade 1", "I got up from bed and did not feel well. My head felt hot. It hurt to talk. I was sick! My dad called the doctor. I had to go see the doctor later that day. I ate soup. I fell asleep for a long time. I woke up and it was time to see the doctor. We took the bus to the doctor. We had to wait for ten minutes. The big door opened. A nice man called my name. He took me to a small room. I got up on a table and the man took my temperature. He put a stick in my mouth to see if my throat had germs. We waited for the doctor to come in. She came in and told me I just had a bad cold. I did not need a shot or medicine. She told me to drink a lot of water. I had to sleep a lot, too. The doctor told me I would get better soon. My dad took me home and I got in bed. I was glad I would feel better."),
  createFluency("orf.1.5", "ORF.1.5 Ways to Take a Trip", "Grade 1", "Do you like to take trips? There are many ways to go! Riding in a car is one way to take a trip. Cars drive to places on land. Cars are best if you have a short trip. They can take you to the store or to work. Cars can also go on longer trips. You may need to stop for more gas. You can also take a trip in a boat. Boats are used for trips on the water. Boats come in all sizes. A cruise ship is large. You can live on a cruise ship for weeks! A rowboat is small. It is perfect for a short trip on a lake. You can take a trip on a plane. Planes are good for very long trips. Planes fly up into the sky with the clouds. A plane can go a long way quickly. Planes come in all sizes too. They give you yummy snacks if you fly in a plane. You can take a trip by train, too. They zip along train tracks. You can look out the window of a train. Some trains sell food. Some even have beds so you can sleep on your trip. Taking a trip is fun!"),
  createFluency("orf.1.6", "ORF.1.6 Try a Bike", "Grade 1", "I have a scooter that I love to ride. I ride it on my street and visit my friends. I made a new friend. He lives near me, but his house is on a dirt road. My scooter will not drive on a dirt road. The wheels are too small. My sister told me I need to try going on a bike. I have never been on a bike! Bikes look fun, but my scooter is easy to ride. All I need are my feet and my helmet! On my scooter, I can jump off if I go too fast. On a bike you have to sit up high. A scooter is low and hard to crash. The best part about a bike is I can have a basket. Then I can bring toys. On my scooter, I have to put on a backpack when I want to bring toys. I think I will try the bike. I will have to be brave because I want to go see my friend. I hope I can do it!"),
  createFluency("orf.1.7", "ORF.1.7 A Visit to Pap's House", "Grade 1", "Zed is going to visit his Pap. He lives in the next town. Zed’s stepmom and dad will drive him to his Pap’s house. He gets to spend the night at his house. Zed gets ready for the trip. First, he needs to pack a bag. Zed finds two shirts and two pants. He puts them into his bag. He gets toothpaste and his toothbrush. He finds a good book, too. Zed puts it all into his bag and zips it up. Wait! He forgot his teddy bear. He pulls his bear off of his bed. Now he can go! He gets in the car with his stepmom and dad. They start the drive to his Pap’s home. Zed looks out the window of the car. He sees a big red truck. He sees a man walking a black dog. Soon they are at his Pap’s home. Zed runs to the door. He rings the doorbell. His Pap opens the door. He gives Zed a big hug. Zed waves goodbye to his stepmom and dad. They go inside. It’s time to eat! Pap made chicken and rice for dinner. After dinner they will have cake. This is going to be the best visit!"),
  createFluency("orf.1.8", "ORF.1.8 A Trip to the Library", "Grade 1", "Lev looked out her window at people going to work. Most of them walked to work or took the bus. It was summer and she did not have much to do. Her mom told her no more games. She was bored! Her mom said to read a book. She did not have any books at home. She had to take a trip to the library. It took her ten minutes to walk there. She opened the big doors and heard lots of kids laughing. A big group of kids was sitting on the floor. A man in a funny hat was telling stories. Lev picked a day that a storyteller was at the library! She sat down with the kids to hear the man’s funny stories. After he was done, he gave every kid a book that he wrote. Lev was so happy to get a new book! She ran home with a smile. She showed her mom that she had something to read. She had the best day at the library."),
  createFluency("orf.1.9", "ORF.1.9 Making Flapjacks", "Grade 1", "Pax wakes up bright and early! Dad will make flapjacks for breakfast. Pax can’t wait to help! He helps Dad get out all the things to make the flapjacks. Dad pulls the flour off the shelf. Pax gets the eggs and milk. Dad gets out the sugar bowl. Pax finds the salt. They put all the things into a big bowl! First, Pax puts some flour in the bowl. He adds one pinch of salt. Dad puts in some sugar. Then Dad cracks two eggs. He puts them both into the bowl. Pax puts one cup of milk into the bowl. Then he gets to mix it all up! Dad sets a pan on the stove. He turns on the stove. Dad must do this part. The stove gets hot. Now, it’s time to cook the flapjacks. Dad will pour the mix onto the hot pan. Dad puts a cup of the flapjack mix onto the pan. The flapjack gets brown on one side. Then he flips it to the other side. He lets it get brown on the next side. He stacks the flapjack on a plate to cool. It’s time to make the next flapjack. When all the flapjacks are made, it’s time to eat! Yum!"),
  createFluency("orf.1.10", "ORF.1.10 Honeybees", "Grade 1", "Bees help keep the planet alive. Bees are yellow and brown. Bees have a lot of hair on their backs. Bees also have wings on their backs to help them fly fast. Bees have six legs and can sting. Bees only sting when they are scared. Bees live in big hives and do many jobs. The queen bee is the leader and lays eggs. Worker bees make food and help build the hive. Bees like flowers and help grow new flowers. Bees can smell flowers from very far away. Bees use flowers to make honey to feed the hive. Honey tastes good. Farmers can grow bees too. Farmers grow bees to make honey. A lot of people like to buy it. Honey can go on food and can go in drinks. Honey makes food and drinks taste better. Some bees are going away. Without bees, flowers and honey may go away. We can help bees by planting new trees and flowers. Trees and flowers give bees homes and food. Bees are good for the planet.")
];
